name: EAS Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install project dependencies
        run: npm ci

      - name: EAS Update
        run: npm run eas update
